# Generated by Django 5.1 on 2024-09-16 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile'),
        ('wordsApp', '0002_category_remove_rutoeng_category_rutoeng_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_dictionary',
            field=models.ManyToManyField(blank=True, to='wordsApp.rutoeng'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordsApp.rutoeng')),
            ],
        ),
    ]
