# Generated by Django 5.1 on 2024-11-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_favorite_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_dictionary',
        ),
        migrations.AddField(
            model_name='profile',
            name='user_level',
            field=models.CharField(choices=[('F', 'Fool'), ('B', 'Begginer'), ('A', 'Advance'), ('P', 'Pro'), ('SP', 'SuperPro')], default='F', max_length=128),
        ),
    ]
