# Generated by Django 5.1 on 2024-08-18 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RusVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='RuToEng',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=256, verbose_name='category names')),
                ('win_rate', models.IntegerField(default=0)),
                ('lose_rate', models.IntegerField(default=0)),
                ('eng_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wordsApp.engversion')),
                ('ru_word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wordsApp.rusversion')),
            ],
        ),
    ]
