# Generated by Django 5.1 on 2024-11-11 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsApp', '0003_alter_category_name_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=256, unique=True, verbose_name='Назвачение слага'),
        ),
    ]
