# Generated by Django 5.1 on 2025-03-11 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordsApp', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rutoeng',
            options={'ordering': ['eng_word__word']},
        ),
    ]
